package com.mainlab.Utilities;

import java.util.EnumMap;

public enum Currencies {
	AFA, ALL, AON, ARS, AMD, AUD, DZD, AZM, BSD, BHD, BDT, BYR, BZD, BMD, BTN, BOB, BAD, BWP, BRL, BND, BGL, BIF, KHR, CAD, CLP, CNY, COP, CRC, HRK, CUP, CYP, CZK, DKK, DJF, DOP, ECS, EGP, SVC, ERN, EEK, ETB, FJD, EUR, GMD, GEL, GTQ, GNS, GYD, HTG, HNL, HKD, HUF, ISK, INR, IDR, IRR, IQD, ILS, JMD, JPY, JOD, KZT, KES, KPW, KRW, KWD, KGS, LAK, LVL, LTL, LBP, LSL, LRD, LYD, MOP, MKD, MWK, MYR, MVR, MTL, MRO, MUR, MXN, MDL, MNT, MAD, MZM, MMK, NAD, NPR, NZD, NIO, NGN, NOK, OMR, PKR, PAB, PYG, PEN, PHP, PLN, QAR, RON, RUB, RWF, XCD, SAR, SCR, SLL, SGD, SIT, SOS, ZAR, LKR, SDD, SRG, SZL, SEK, CHF, SYP, TWD, TJR, TZS, THB, TOP,TTD, TND, TRY, TMM, AED, UGX, UAH, GBP, USD, UYU, UZS, VEB, VND, YER, YUD, ZMK, ZWD;
}